stages:
  - build
  - deploy

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE/expense-tracker-api

# Build and push Docker image to GitLab Container Registry
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME

# Deploy to AWS EC2 (example via SSH)
deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
  script:
    - echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
    - ssh -i private_key -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST '
      docker pull $CI_REGISTRY_IMAGE/expense-tracker-api &&
      docker stop expense-tracker-api || true &&
      docker rm expense-tracker-api || true &&
      docker run -d --name expense-tracker-api --env-file .env -p 4000:4000 $CI_REGISTRY_IMAGE/expense-tracker-api
      '
