version: "3.8"

services:
  api:
    build: .
    container_name: expense-tracker-api
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: expense-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
